import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Providers from "./Providers";

const roboto = Roboto({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div>
          <Navbar />
          <main className="py-20 max-w-[90%] sm:max-w-[80%] mx-auto bg-slate-900 min-h-[calc(100vh-60px)] ">
            <Providers>{children}</Providers>
          </main>
        </div>
      </body>
    </html>
  );
}
